# [(c) or copyright] 2019 Amazon Web Services, Inc. All Rights Reserved. This AWS Content is subject to the terms of the Basic Ordering Agreement Contract No. [2018-17120800001/Order No. ABC123 or Agency-specific contract number]
AWSTemplateFormatVersion:  2010-09-09
Transform: AWS::Serverless-2016-10-31

Description:  >-
  This template deploys the Lambda functions and API Gateway
  
Parameters:
  pParameter1:
    Description: Param Description
    Type: Stringp
    
  Parameter2:
    Description: Param Description
    Type: String

Resources:
  #API Gateway
  rApi:
  	Type: AWS::Serverless::Api
  	Properties:
    	StageName: prod
    	DefinitionUri: swagger.yml
    	
Outputs:
  oStackName:
    Description: This is the stack name.
    Value: !Ref 'AWS::StackName'
    Export:
      Name: !Sub '${AWS::StackName}-oStackName'
			